### ISSUE TITLE
Essential Genes portal query design: front end

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#354]
Design suggestion: 

![Screenshot 2020-06-08 at 12.21.27 (1).png](https://images.zenhubusercontent.com/5e2731c352024f33e54b74eb/a77fb224-7189-4f1e-ac80-70d2a0f4a77d)

**Comment by jmason-ebi** [comment]
Use the new front end framework that federico is putting together for the combined lifestage ticket.

**Comment by viomunoz** [comment]
This will be stand alone to which we will be linking from #375 (and potentially other pages).

**Comment by jmason-ebi** [comment]
Preliminary tool:
https://wwwdev.ebi.ac.uk/~federico/phenotype-data/essential-genes

**Comment by viomunoz** [comment]
**Tests performed:**
Mouse genes:
MGI:1929293
MGI:3512453
MGI:2441763
MGI:3647736
MGI:2385336

Human genes:
HGNC:24579
HGNC:4519
HGNC:24018
HGNC:1839
HGNC:11424
HGNC:21332




**Requirements for a final product** 

- [ ] **Display mouse phenotypes**
These are used to caculate the VP and VN categories, and are useful in patients' diagnosis.

hom_top_level_mp_terms
hom_mp_terms
het_top_level_mp_terms
het_mp_terms
hem_top_level_mp_terms
hem_mp_terms

**Identifiers:**
- [ ] Ability to modify what the user copy-pasted. For example, MGI: 2385336 or MGI1929293, rather than delete and write anew.
- [ ] Ability to paste a list. For example, users may have a list with 20 genes, 500 genes, etc. Ideally a user may likeo be able to paste genes sperated by new line, spaces or tabs
- [ ] Ability to upload a list (can leave for second iteration)
- [ ] Ability to remove / delete all input easily. For example, user pasted 20 mouse genes and now user wants  to paste 20 human genes. (User doesn't want to click 20 times on crosses to delete the genes in the input field.)
- [ ]  Output table to disappear when genes are removed from input list.
A box where users can copy and paste text may be a good solution.

**Attributes:**
- [ ] Remove "combined" from "IMPC combined primary / adult viability"; should be: "IMPC primary / adult viability"
- [ ] Change "Select ortholog attributes" to "Additional attributes"


**Output table:**
- [ ] Order of rows to match gene order in input list or, alternatively, be sorted, e.g. by identifier, from smallest to biggest.
- [ ] Order of columns: we need a default column order  [see below #1], also for the attributes (in case users compare different tables, same order of columns is best rather than order in which attributes were selected)
- [ ] Columns that we need to display [see below #2]
- [ ] Column headers to something most users can hopefully understand [see below #3]
- [ ] IDG family: when "NULL" leave blank (consitent with other fields with no data) or have  a string such as e.g. "no_data"

**Downloadable file:**
- [ ] Column and row order to match screen display.

**IMPC secondary / embryo viability:**
- [ ] Need to look into the backend

- [ ] **Provide introductory text and finalise documentation**

**Comment by viomunoz** [comment]
**[1] Column order and columns to display:**

- Input from user, header "Input" (first column; subsequent fields are blank if not found in our database; most users will find this is helpful in their dowstream processes)
- Gene identifiers of genes requested: gene accession id, ensembl id, gene symbol, chr, start, end, gene name, gene type, synonyms
- Gene identifiers of orthologues 
- Orthologue relationship: o_support, o_support_count, o_category, o_is_max_human_to_mouse, o_is_max_mouse_to_human
- Gene features: achilles gene effect, iav, fusil, clingen, idg, gnomad
It is possible we are requested to display more features from gnomad but, for the time being, we can restrict it to what we have been using.

**Comment by viomunoz** [comment]
**[2] Column names
Mapping:**	

- mg >> mouse
- age >> achilles
- gnp >> gnomad
- hgnc >> human
- idg >> idg

**Comment by viomunoz** [comment]
Revision of tool: https://wwwdev.ebi.ac.uk/~federico/phenotype-data/essential-genes

Regarding [2] column names (above):
Column names looking good, still these changes are needed to tick box above:
o >> orthologue
mgs >> mouse
hgs >> human
cav >> impc_via
f >> fusil

Regarding [1] column order (above):
Order looking good, only gene features modification required to tick this box, as it will be more logical to our users:
Good to have achilles gene effect next to viability information (cav_category) and fusil information (f_ columns), as these are directly related. 
As there is also the allele, let's have this order as it will be more logical to users: o_support_count, cav_allele_symbol, cav_category, achilles_mean_gene effect, f_bin, f_bin_code

All the other points still need to be implemented?
I will be making new tickets.

**Comment by viomunoz** [comment]
This ticket has been superseded for all the above tickets.
