### ISSUE TITLE
Data Release Report Standardisation

### ISSUE THREAD

**Issue by mrelac-ebi** [mpi2/PhenotypeData#413]
**Description**
The new ETL data release process has optimised the data release build and, as a side effect, some unnecessary fields (required by the compiler but not participating in the report) for the DR reports were removed; thus, some reports do not compile.

Additionally, with each new data release, the BMD reports take more and more time to complete (1.5 hours apiece). Also, the BMD report names do not describe their content.

@viomunoz has proposed the following regarding ftp, release, and report documentation (currently there is no public documentation for reports):
[README_files_for_FTP_site.txt](https://github.com/mpi2/PhenotypeData/files/5061866/README_files_for_FTP_site.txt)

Violeta's notes:
[https://app.zenhub.com/files/37316577/d7d7f4a9-0789-4a81-b361-1b9cc12873aa/download](https://app.zenhub.com/files/37316577/d7d7f4a9-0789-4a81-b361-1b9cc12873aa/download)

Mike's notes:
[https://app.zenhub.com/files/37316577/12e044ce-70f4-4a33-ab9d-d04344751b39/download](https://app.zenhub.com/files/37316577/12e044ce-70f4-4a33-ab9d-d04344751b39/download)

**Summary**

1. **Bug:** Some reports do not compile
1. **Enhancement, Design:** Reduce run time of reports if possible
1. **Enhancement, Content:** Review each report's content and fields. Standardise names and formats
1. **Enhancement, Content:** Remove trailing 'xxxReport' from all report java classes as it's confusing and adds no value
1. **Enhancement, Content:** Rename reports that do not describe their content
    - bmdStatsReport -> boneMineralDensity
    - bmdStatsGlucoseConcentrationReport -> glucoseConcentration
    - bmdStatsGlucoseResponseReport -> glucoseResponse
    - hitsPerLineReport -> phenotypeHitsPerLine
    - hitsPerParameterAndProcedureReport -> phenotypeHitsPerParameterAndProcedure
    - phenotypeHitsReport -> phenotypeHitsPerTopLevelMPTerm
    - phenotypeOverviewPerGeneReport -> phenotypeHitsPerGene

1. **Enhancement:** Create public document describing each report

**Acceptance Criteria**

- [x] All reports compile
- [x] A public location has been chosen for report documentation
- [x] Acceptance criteria for each report has been met

Acceptance criteria for each report:

- Report run time has been optimised if possible
- Report name adequately describes its content
- Report fields have been reviewed and added/removed as necessary
    - Rename 'Strain' to 'Background Strain'
    - Standardise accession id columns to xxx Accession Id (e.g. Gene, Allele, Strain)
    - General column order preference: Gene, Allele, Strain, Colony, Center, Parameter, with symbols before accession ids
- Report documentation has been installed in the report document location chosen above

***Reports***
From the new results README.md:
## Report filename mapping
Beginning with data release 12.0, the `reports` directory is 
called `results` and the contents of the old `csv` directory 
have been rolled into the new `results` directory. Some old reports 
were removed owing to both expensive maintenance, long completion 
times, of limited or no use, and/or ambiguous/misleading data. The 
remaining files in the `report` directory were renamed to better 
represent their content. Following is a map of reports removed, reports 
renamed, and files merged from the old `csv` directory.

| Original Report Name               | Action     | New Report Name                       | 
| --------------------               | ------     | ---------------                       |
| dataOverviewReport                 | renamed    | dataOverview                          |
| fertilityReport                    | renamed    | fertility                             |
| 3I_genotype_phenotype              | from `.csv`| genotype-phenotype-assertions-3I      |
| ALL_genotype_phenotype             | from `.csv`| genotype-phenotype-assertions-ALL     |
| EuroPhenome_genotype_phenotype     | from `.csv`| genotype-phenotype-assertions-EUROPHENOME |
| IMPC_genotype_phenotype            | from `.csv`| genotype-phenotype-assertions-IMPC    |
| MGP_genotype_phenotype             | from `.csv`| genotype-phenotype-assertions-MGP     |
| laczExpressionReport               | renamed    | laczExpression                        |
| phenotypeOverviewPerGeneReport     | renamed    | phenotypeHitsPerLine                  |
| hitsPerParameterAndProcedureReport | renamed    | phenotypeHitsPerParameterAndProcedure |
| phenotypeHitsReport                | renamed    | phenotypeHitsPerTopLevelMPTerm        |
| procedureCompletenessAllReport     | renamed    | procedureCompleteness                 |
| IMPC_ALL_statistical_results       | from `.csv`| statistical-results-ALL               |
| viabilityReport                    | renamed    | viability                             |
| zygosityReport                     | renamed    | zygosity                              |
| ALL_MPATH_genotype_phenotype       | removed    |                                       |
| bmdStatsGlucoseConcentrationReport | removed    |                                       |
| bmdStatsGlucoseResponseReport      | removed    |                                       |
| bmdStatsReport                     | removed    |                                       |
| impcGafReport                      | removed    |                                       |
| impcPValuesReport                  | removed    |                                       |
| metabolismCalorimetryReport        | removed    |                                       |
| metabolismCBCReport                | removed    |                                       |
| metabolismDEXAReport               | removed    |                                       |
| metabolismIPGTTReport              | removed    |                                       |
| procedureCompletenessImpcReport    | removed    |                                       |

**Addenda**
- [ ] procedureCompletenessAll and procedureCompletenessImpc are being replaced with a single report, procedureCompleteness.
- [ ] procedureCompleteness row granularity is: 1 unique colonyId, zygosity, and life stage per row.

**Comment by mrelac-ebi** [comment]
Report / ftp rewrite is done in time for DR12.0
