### ISSUE TITLE
"Disease Models" section on Gene Page needs fixes

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#485]
**- Documentation needs to cover**
- [x] API access (ticket #467)
- [x] Display on gene page (ticket #465)

**- Display on gene page (ticket #486)**
- [ ] Terminology: headers column 1 and 2
- [ ] Notation: zygosity to follow convention
- [ ] Links: needed 
- [ ] IMPC icon: unappropriate size
- [ ] Phenogrid widget: too small, oudated version?

**Comment by rwilson-ebi** [comment]
This can be closed. The work was done in the UX sessions and has been implemented.
